name: Deploy_Cloud_Run

on:
  release:
    types: [ published ]

jobs:

  deploy:

    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:

      - name: Login
        uses: google-github-actions/setup-gcloud@master
        with:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME  --build-arg "GITHUB_USER_TOKEN=${{ secrets.GO_MODULES_TOKEN }}"

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        env:
          VARS: "ENVIRONMENT=production"
        run: gcloud run deploy ${{ secrets.GCP_APP_NAME }} --project ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region europe-west1 --allow-unauthenticated --memory 256Mi  --set-env-vars ${VARS}